// Extracts the site's <style> block from ../index.html into dist/styles.css.
// index.html is the single source of truth for the design system's CSS —
// this script means the library can never drift from the live site.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const siteHtml = readFileSync(join(here, '..', '..', 'index.html'), 'utf8');

const m = siteHtml.match(/<style>([\s\S]*?)<\/style>/);
if (!m) {
  console.error('extract-css: no <style> block found in index.html');
  process.exit(1);
}

const header = `/* Generated by scripts/extract-css.mjs from the live site's index.html — do not edit.
 * Re-run \`npm run build\` after changing the site's styles. */
`;

// The site reveals sections on scroll via an IntersectionObserver that adds .in;
// without that JS, anything carrying .reveal sits at opacity:0 forever. The
// design system has no scroll choreography, so neutralise it here.
const footer = `
/* design-system: neutralise the site's scroll-reveal choreography (no observer here) */
.reveal{opacity:1;transform:none;}
`;

mkdirSync(join(here, '..', 'dist'), { recursive: true });
writeFileSync(join(here, '..', 'dist', 'styles.css'), header + m[1] + footer);
console.log(`extract-css: wrote dist/styles.css (${m[1].length} chars from index.html)`);
